{% set name = "recordclass" %}
{% set version = "0.22.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/recordclass-{{ version }}.tar.gz
  sha256: 64d1ad1a43d97b1d7754317ea5e3903e8094bca7af9f2a08af9ff44b4c273c56

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - recordclass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intellimath/recordclass
  summary: Mutable variant of namedtuple -- recordclass, which support assignments, compact dataclasses and other memory saving variants.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - druvus
